version: '3'

services:
  api:
    container_name: template-api
    build:
        context: .
        dockerfile: docker/Dockerfile
        args:
          requirements: /app/docker/requirements/dev.txt
    command: "/app/scripts/start-reload.sh"
    depends_on:
      - db
    env_file:
      - "docker/.env"
    ports:
      - "8000:${PORT:-80}"
      - "8001:8001"
    volumes:
      - ".:/app"
  db:
    container_name: template-api-db
    image: postgres:11.7
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=template-api
    volumes:
      - template-api-db:/var/lib/postgresql/data/
  wdb:
    container_name: wdb
    image: kozea/wdb
    ports:
      - "1984:1984"
volumes:
  template-api-db:
