repos:
    -   repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v2.3.0
        hooks:
        -   id: end-of-file-fixer
        -   id: trailing-whitespace
        -   id: check-docstring-first
        -   id: requirements-txt-fixer
        -   id: check-ast
        -   id: check-merge-conflict
    -   repo: https://github.com/asottile/add-trailing-comma
        rev: v2.0.1
        hooks:
        -   id: add-trailing-comma
    -   repo: https://github.com/asottile/reorder_python_imports
        rev: v2.1.0
        hooks:
        -   id: reorder-python-imports
    -   repo: https://github.com/ambv/black
        rev: stable
        hooks:
        -   id: black
            language_version: python3.7
